version: '2'
volumes:
  api_postgres_data: {}
  api_redis_data: {}
services:
  api_django:
    env_file:
      - ./envs/common/api/common.env
      - ./envs/common/api/django.env
  api_postgres:
    image: ${HUB_HOST}/${PROJECT_NAME}/api-postgres:${PROJECT_VERSION}
    volumes:
      - api_postgres_data:/var/lib/postgresql/data
  api_redis:
    image: redis:3.2.4
    volumes:
      - api_redis_data:/data
  api_celery_worker:
    command: celery worker -A celery_app -l debug
    env_file:
      - ./envs/common/api/common.env
      - ./envs/common/api/celery/worker.env
  api_nginx:
    image: ${HUB_HOST}/${PROJECT_NAME}/api-nginx:${PROJECT_VERSION}
